version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=ois123
    ports:
      - '5432:5432'
    volumes:
      - D:/DB/postgres:/var/lib/postgresql/data